/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import lapr.project.controller.AvaliarCandidaturaController;
import lapr.project.model.Candidatura;
import lapr.project.model.CandidaturaDemonstracao;
import lapr.project.model.CandidaturaExposicao;
import lapr.project.model.CentroExposicoes;
import lapr.project.model.Demonstracao;
import lapr.project.model.Exposicao;
import lapr.project.model.FAE;
import lapr.project.model.Local;
import lapr.project.model.Utilizador;
import lapr.project.utils.Data;

/**
 *
 * @author catarinarib
 */
public class AvaliarCandidaturaUI extends javax.swing.JFrame {

    private final CentroExposicoes ce;
    private MenuUI menu;
    private Exposicao exposicao;
    private FAE fae;
    private CandidaturaExposicao candExp;
    private CandidaturaDemonstracao candDemo;
    private final AvaliarCandidaturaController controller;
    private String tpCand;
    private QuestionarioFAECand questionario;

    /**
     * Creates new form AvaliarCandidaturaUI
     *
     * @param ce
     * @param fae
     */
    public AvaliarCandidaturaUI(final CentroExposicoes ce, FAE fae, String tpCand) {
        this.fae = fae;
        this.ce = ce;
        this.tpCand = tpCand;
        this.controller = new AvaliarCandidaturaController(ce, fae);
        initComponents();
        setVisible(true);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int result = JOptionPane.showConfirmDialog(
                        AvaliarCandidaturaUI.this, "Tens a certeza?");
                if (result == JOptionPane.OK_OPTION) {

                    AvaliarCandidaturaUI.this.setDefaultCloseOperation(
                            JDialog.DISPOSE_ON_CLOSE);
                    AvaliarCandidaturaUI.this.setVisible(false);
                    AvaliarCandidaturaUI.this.dispose();
                    JFrame MenuUI = new MenuUI(ce);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        label3 = new java.awt.Label();
        jSeparator4 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox<>();
        label4 = new java.awt.Label();
        jSeparator5 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avaliar Candidatura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        String [] exposicoes = new String[100];
        int i=0;
        if(!controller.getListaExposicoesFAE(fae.getUtilizador()).isEmpty()){
            for(Exposicao e : controller.getListaExposicoesFAE(fae.getUtilizador())){
                exposicoes[i]=e.getTitulo();
                i++;
            }
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(exposicoes));

        label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label1.setText("Exposição:");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Candidatura:");

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("Informação Candidatura:");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setEnabled(false);
        jScrollPane2.setViewportView(jList2);

        jButton2.setText("Continuar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Demonstração:");

        jComboBox2.setEnabled(false);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Continuar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        label3.setBackground(new java.awt.Color(153, 153, 255));
        label3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label3.setText("Decisão:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aceita", "Não Aceita" }));

        label4.setBackground(new java.awt.Color(153, 153, 255));
        label4.setText("Justificação:");

        jButton4.setBackground(new java.awt.Color(153, 255, 204));
        jButton4.setText("Questionário");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 153, 255));
        jButton6.setText("Guardar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);
        jTextArea2.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton3.setEnabled(false);
        jComboBox3.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (this.tpCand.equalsIgnoreCase("exposicao")) {
            jButton2.setEnabled(true);
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {

                    String expo = jComboBox1.getSelectedItem() + "";
                    jComboBox1.setEnabled(false);

                    if (!expo.isEmpty()) {
                        for (Exposicao e : ce.getRegistoExposicoes().getListaExposicoes()) {

                            if (e.getTitulo().equalsIgnoreCase(expo)) {
                                exposicao = e;
                            }

                        }

                    }

                    controller.selecionaExposicao(exposicao);

                    final String[] candidaturas = new String[100];
                    int cont = 0;
//                if (!controller.getAvaliaveis(fae).isEmpty()) {
//                    for (Candidatura c : controller.getAvaliaveis(fae)) {
//                        candidaturas[cont] = c.toString();
//                        cont++;
//                    }
//                }

                    if (!exposicao.getListaCandidaturas().getListCandidaturas().isEmpty()) {
                        for (Candidatura c : exposicao.getListaCandidaturas().getListCandidaturas()) {
                            candidaturas[cont] = c.toString();
                            cont++;
                        }
                    }

                    jList2.setModel(new javax.swing.AbstractListModel<String>() {

                        public int getSize() {
                            return candidaturas.length;
                        }

                        public String getElementAt(int i) {
                            return candidaturas[i];
                        }
                    });

                    jList2.setEnabled(true);

                }
            }
            );
            jButton1.setEnabled(false);
        } else {
            jComboBox1.setEnabled(false);
            jButton1.setEnabled(false);
            jComboBox2.setEnabled(true);
            jButton3.setEnabled(true);

            String expo = jComboBox1.getSelectedItem() + "";
            jComboBox1.setEnabled(false);

            if (!expo.isEmpty()) {
                for (Exposicao e : ce.getRegistoExposicoes().getListaExposicoes()) {

                    if (e.getTitulo().equalsIgnoreCase(expo)) {
                        exposicao = e;
                    }

                }

            }
            controller.selecionaExposicao(exposicao);

            String[] demonstracoes = new String[100];
            int i = 0;
//            if (!exposicao.getListaDemonstracoes().getListaDemonstracoesDisponiveis().isEmpty()) {
//                for (Demonstracao d : exposicao.getListaDemonstracoes().getListaDemonstracoesDisponiveis()) {
//                    demonstracoes[i] = d.getCodigo();
//                    i++;
//                }
//
//            }

            if (!exposicao.getListaDemonstracoes().getListaDemonstracao().isEmpty()) {
                for (Demonstracao d : exposicao.getListaDemonstracoes().getListaDemonstracao()) {
                    demonstracoes[i] = d.getCodigo();
                    i++;
                }

            }

            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(demonstracoes));

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jList2.setEnabled(false);
        jButton2.setEnabled(false);

//        if (!controller.getAvaliaveis(fae).isEmpty()) {
//            for (Candidatura c : controller.getAvaliaveis(fae)) {
//                if(c.getEmailRep().equalsIgnoreCase(jList2.getSelectedValue())){
//                    controller.selectCandidatura(c);
//                      if(tpCand.equalsIgnoreCase("exposicao")){
//                           this.candExp = (CandidaturaExposicao) c;
//                      }else{
//                          this.candDemo=(CandidaturaDemonstracao) c;
//                      }
////                }
//            }
//        }
        if (!exposicao.getListaCandidaturas().getListCandidaturas().isEmpty()) {
            for (Candidatura c : exposicao.getListaCandidaturas().getListCandidaturas()) {
                if (c.getEmailRep().equalsIgnoreCase(jList2.getSelectedValue())) {
                    controller.selectCandidatura(c);
                    this.candExp = (CandidaturaExposicao) c;
                }
            }
        }

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {

                if (tpCand.equalsIgnoreCase("exposicao")) {
                    jTextArea1.setText("Nome Empresa: " + candExp.getnomeEmpresa() + "\nMorada: " + candExp.getMorada()
                            + "\nTelemovel: " + candExp.getTelemovel() + "\nArea: " + candExp.getArea() + "\nNºConvites: " + candExp.getConvites()
                            + "\nLista de Demonstrações:\n" + candExp.getListaDemonstracoes().toString());

                    jTextArea1.setEditable(false);
                    jComboBox3.setEnabled(true);
                    jTextArea2.setEditable(true);
                    jButton4.setEnabled(true);

                } else {
                    jTextArea1.setText("Demonstracao: " + candDemo.getDemonstracao());

                    jTextArea1.setEditable(false);
                    jComboBox3.setEnabled(true);
                    jTextArea2.setEditable(true);

                }
            }
        }
        );
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuUI m = new MenuUI(ce);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        try {

            if (tpCand.equalsIgnoreCase("exposicao")) {
                String fae = this.fae.getID();
                String candE = this.candExp.getEmailRep();
                String decisao = jComboBox3.getSelectedItem() + "";
                String txt = jTextArea2.getText();

                if (txt == null || txt.trim().isEmpty()) {
                    throw new IllegalArgumentException("Justificação vazia!");
                }
                
                int temaExpo = questionario.temaExpo();
                int adqCandExpo = questionario.adqCandExpo();
                int adqCandDemo = questionario.adqCandDemo();
                int adqNumCov = questionario.adqNumConv();
                int recGlobal=questionario.recGlobal();
                
                

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                    menu,
                    "Tem que introduzir números válidos.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    menu,
                    ex.getMessage(),
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {

                jComboBox2.setEnabled(false);

                final String[] candidaturas = new String[100];
                int cont = 0;
//                if (!controller.getAvaliaveis(fae).isEmpty()) {
//                    for (Candidatura c : controller.getAvaliaveis(fae)) {
//                        candidaturas[cont] = c.toString();
//                        cont++;
//                    }
//                }

                if (!exposicao.getListaCandidaturas().getListCandidaturas().isEmpty()) {
                    for (Candidatura c : exposicao.getListaCandidaturas().getListCandidaturas()) {
                        candidaturas[cont] = c.toString();
                        cont++;
                    }
                }

                jList2.setModel(new javax.swing.AbstractListModel<String>() {

                    public int getSize() {
                        return candidaturas.length;
                    }

                    public String getElementAt(int i) {
                        return candidaturas[i];
                    }
                });

                jList2.setEnabled(true);

            }
        }
        );
        jButton1.setEnabled(false);
        jButton2.setEnabled(true);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        this.questionario = new QuestionarioFAECand();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaliarCandidaturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaliarCandidaturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaliarCandidaturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaliarCandidaturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CentroExposicoes ce = new CentroExposicoes();
                Utilizador u = new Utilizador("joao", "jo", "asd@centro.pt", "aA;2", "ddddd");
                ce.getRegistoUtilizadores().addUtilizador(u);
                Utilizador u1 = new Utilizador("carol", "carol", "carold@centro.pt", "aA;2", "ddddd");
                ce.getRegistoUtilizadores().addUtilizador(u1);
                Local l = new Local("Porto");
                ce.getRegistoLocais().addLocal(l);
                Data dat = new Data(2016, 07, 22, 22, 22, 22);
                Exposicao e = new Exposicao("Titulo", "Descricao", dat, dat, l, dat, dat,
                        dat, dat);
                ce.getRegistoExposicoes().getListaExposicoes().add(e);
                CandidaturaExposicao ec = new CandidaturaExposicao("sd@centro.pt", "nome empresa", "morada", 912222222, 2, 2);
                CandidaturaExposicao cand = new CandidaturaExposicao("cat@centro.pt", "nome empresa", "morada", 912222222, 2, 2);
                e.getListaCandidaturas().addCandidatura(ec);
                e.getListaCandidaturas().addCandidatura(cand);
                FAE fae = new FAE(u);
                e.getListaFAES().addFae(fae);
                e.getListaAtribuicoes().newAtribuicao(ec, fae);
                Demonstracao demo = new Demonstracao("111", "sdf");
                e.getListaDemonstracoes().addDemonstracao(demo);
                new AvaliarCandidaturaUI(ce, fae, "exposicao").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
