/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

/**
 *
 * @author catarinarib
 */
public class CriarExposicaoUI extends javax.swing.JFrame {

    /**
     * Creates new form CriarExposicaoUI
     */
    public CriarExposicaoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        textArea1 = new java.awt.TextArea();
        label3 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        textField4 = new java.awt.TextField();
        label6 = new java.awt.Label();
        jLabel5 = new javax.swing.JLabel();
        textField5 = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textField6 = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        textField7 = new java.awt.TextField();
        textField8 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("Título:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, -1));
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, -1));

        label2.setText("Descrição:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 60, -1));
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 200, 60));

        label3.setText("Data Inicio:");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, -1));
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 150, -1));

        jLabel2.setText("Ex: aaaa/mm/dd-hh:mm:ss");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 160, 20));

        label4.setText("Data Fim:");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 70, -1));
        getContentPane().add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 150, -1));

        jLabel3.setText(". Inicio Submissão de Candidaturas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 210, 20));

        jLabel4.setText("Ex: aaaa/mm/dd-hh:mm:ss");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 150, -1));

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setText("Datas:");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 419, 10));
        getContentPane().add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 160, -1));

        label6.setText("Ex: aaaa/mm/dd-hh:mm:ss");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 160, -1));

        jLabel5.setText(".Fim Submissão de Candidaturas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 210, 20));
        getContentPane().add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 160, -1));

        jLabel6.setText(".Inicio da Deteção de Conflitos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 200, 20));

        jLabel8.setText(".Fim de Avaliação de Candidaturas:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 200, 20));
        getContentPane().add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 160, -1));

        jLabel7.setText(".Fim de Atualização de Conflitos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 200, 20));
        getContentPane().add(textField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 160, -1));
        getContentPane().add(textField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/criarExposicao2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 560));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarExposicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarExposicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarExposicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarExposicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarExposicaoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    private java.awt.TextField textField7;
    private java.awt.TextField textField8;
    // End of variables declaration//GEN-END:variables
}
