/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;
import lapr.project.model.CentroExposicoes;

/**
 *
 * @author catarinarib
 */
public class MenuUI extends JFrame {

    private CentroExposicoes ce;
    /**
     * Creates new form MenuUI
     */
    public MenuUI(CentroExposicoes ce) {
        this.ce=ce;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu38 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu35 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu26 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu29 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu32 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu41 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu45 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setBackground(new java.awt.Color(153, 153, 255));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(900, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colour-background-back-ground-lumiere-abstract-media-wallpapers-166067.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jMenu1.setText("Ficheiro");

        jMenuItem27.setText("Importar");
        jMenu1.add(jMenuItem27);

        jMenu4.setText("Exportar");

        jMenuItem28.setText("Exposições");
        jMenu4.add(jMenuItem28);

        jMenuItem29.setText("jMenuItem29");
        jMenu4.add(jMenuItem29);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Utilizadores");

        jMenuItem25.setText("Confirmar Perfil de Utilizadores");
        jMenu2.add(jMenuItem25);

        jMenuItem26.setText("Definir FAE");
        jMenu2.add(jMenuItem26);

        jMenuBar1.add(jMenu2);

        jMenu38.setText("Recursos");

        jMenuItem24.setText("Definir Recusos");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu38.add(jMenuItem24);

        jMenuBar1.add(jMenu38);

        jMenu7.setText("Exposição");

        jMenuItem23.setText("Criar Exposição");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem23);

        jMenuBar1.add(jMenu7);

        jMenu35.setText("Demonstração");

        jMenuItem21.setText("Criar Demonstração");
        jMenu35.add(jMenuItem21);

        jMenuItem22.setText("Confirmar Interesse");
        jMenu35.add(jMenuItem22);

        jMenuBar1.add(jMenu35);

        jMenu13.setText("Candidatura");

        jMenu14.setText("Registar Candidatura");

        jMenuItem9.setText("Exposição");
        jMenu14.add(jMenuItem9);

        jMenuItem10.setText("Demonstração");
        jMenu14.add(jMenuItem10);

        jMenu13.add(jMenu14);

        jMenu17.setText("Alterar Candidatura");

        jMenuItem11.setText("Exposição");
        jMenu17.add(jMenuItem11);

        jMenuItem12.setText("Demonstração");
        jMenu17.add(jMenuItem12);

        jMenu13.add(jMenu17);

        jMenu26.setText("Remover Candidatura");

        jMenuItem13.setText("Exposição");
        jMenu26.add(jMenuItem13);

        jMenuItem14.setText("Demontração");
        jMenu26.add(jMenuItem14);

        jMenu13.add(jMenu26);

        jMenu29.setText("Listar Candidaturas Removidas");

        jMenuItem15.setText("Exposição");
        jMenu29.add(jMenuItem15);

        jMenuItem16.setText("Demonstração");
        jMenu29.add(jMenuItem16);

        jMenu13.add(jMenu29);

        jMenu20.setText("Avaliar Candidatura");

        jMenuItem17.setText("Exposição");
        jMenu20.add(jMenuItem17);

        jMenuItem18.setText("Demonstração");
        jMenu20.add(jMenuItem18);

        jMenu13.add(jMenu20);

        jMenu23.setText("Decidir Candidatura");

        jMenuItem19.setText("Exposição");
        jMenu23.add(jMenuItem19);

        jMenuItem20.setText("Demonstração");
        jMenu23.add(jMenuItem20);

        jMenu13.add(jMenu23);

        jMenuBar1.add(jMenu13);

        jMenu32.setText("Stands");

        jMenuItem6.setText("Criar Stand");
        jMenu32.add(jMenuItem6);

        jMenuItem7.setText("Confirmar Interesse em Stand");
        jMenu32.add(jMenuItem7);

        jMenuItem8.setText("Atribuir Stand");
        jMenu32.add(jMenuItem8);

        jMenuBar1.add(jMenu32);

        jMenu41.setText("Estatistica");

        jMenuItem3.setText("Estatistica Candidatura");
        jMenu41.add(jMenuItem3);

        jMenuItem4.setText("Ranking Keywords");
        jMenu41.add(jMenuItem4);

        jMenuItem5.setText("Estatistica FAE");
        jMenu41.add(jMenuItem5);

        jMenuBar1.add(jMenu41);

        jMenuBar1.add(Box.createGlue());
        jMenu9.setText("Perfil");

        jMenuItem1.setText("Alterar Perfil");
        jMenu9.add(jMenuItem1);

        jMenuBar1.add(jMenu9);

        jMenu45.setText("sair");

        jMenuItem2.setText("sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu45.add(jMenuItem2);

        jMenuBar1.add(jMenu45);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        dispose();
        CriarExposicaoUI c = new CriarExposicaoUI(ce);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables

    
}
