/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import javax.swing.Box;

/**
 *
 * @author catarinarib
 */
public class MenuUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuUI
     */
    public MenuUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenu40 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(900, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colour-background-back-ground-lumiere-abstract-media-wallpapers-166067.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jMenu1.setText("Ficheiro");

        jMenu3.setText("Importar");
        jMenu1.add(jMenu3);

        jMenu4.setText("Exportar");
        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Utilizadores");

        jMenu12.setText("Confirmar Perfil de Utilizadores");
        jMenu2.add(jMenu12);

        jMenu11.setText("Definir FAE");
        jMenu2.add(jMenu11);

        jMenuBar1.add(jMenu2);

        jMenu38.setText("Recursos");

        jMenu40.setText("Definir Recursos");
        jMenu38.add(jMenu40);

        jMenuBar1.add(jMenu38);

        jMenu7.setText("Exposição");

        jMenu8.setLabel("Criar Exposição");
        jMenu7.add(jMenu8);

        jMenuBar1.add(jMenu7);

        jMenu35.setText("Demonstração");

        jMenu36.setText("Criar Demonstração");
        jMenu35.add(jMenu36);

        jMenu39.setText("Confirmar Interesse ");
        jMenu35.add(jMenu39);

        jMenuBar1.add(jMenu35);

        jMenu13.setText("Candidatura");

        jMenu14.setText("Registar Candidatura");

        jMenu15.setText("Exposição");
        jMenu14.add(jMenu15);

        jMenu16.setText("Demonstração");
        jMenu14.add(jMenu16);

        jMenu13.add(jMenu14);

        jMenu17.setText("Alterar Candidatura");

        jMenu18.setText("Exposição");
        jMenu17.add(jMenu18);

        jMenu19.setText("Demonstração");
        jMenu17.add(jMenu19);

        jMenu13.add(jMenu17);

        jMenu26.setText("Remover Candidatura");

        jMenu27.setText("Exposição");
        jMenu26.add(jMenu27);

        jMenu28.setText("Demonstração");
        jMenu26.add(jMenu28);

        jMenu13.add(jMenu26);

        jMenu29.setText("Listar Candidaturas Removidas");

        jMenu30.setText("Exposição");
        jMenu29.add(jMenu30);

        jMenu31.setText("Demonstração");
        jMenu29.add(jMenu31);

        jMenu13.add(jMenu29);

        jMenu20.setText("Avaliar Candidatura");

        jMenu21.setText("Exposição");
        jMenu20.add(jMenu21);

        jMenu22.setText("Demonstração");
        jMenu20.add(jMenu22);

        jMenu13.add(jMenu20);

        jMenu23.setText("Decidir Candidatura");

        jMenu24.setText("Exposição");
        jMenu23.add(jMenu24);

        jMenu25.setText("Demonstração");
        jMenu23.add(jMenu25);

        jMenu13.add(jMenu23);

        jMenuBar1.add(jMenu13);

        jMenu32.setText("Stands");

        jMenu33.setText("Criar Stand");
        jMenu32.add(jMenu33);

        jMenu37.setText("Confirmar Interesse em Stand");
        jMenu32.add(jMenu37);

        jMenu34.setText("Atribuir Stand");
        jMenu32.add(jMenu34);

        jMenuBar1.add(jMenu32);

        jMenu41.setText("Estatistica");

        jMenu42.setText("Estatística Candidatura");
        jMenu41.add(jMenu42);

        jMenu43.setText("Ranking Keywords");
        jMenu41.add(jMenu43);

        jMenu44.setText("Estatistica FAE");
        jMenu41.add(jMenu44);

        jMenuBar1.add(jMenu41);

        jMenuBar1.add(Box.createGlue());
        jMenu9.setText("Perfil");

        jMenu10.setText("Alterar Perfil");
        jMenu9.add(jMenu10);

        jMenuBar1.add(jMenu9);

        jMenu6.setText("Sair");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
